language: python
arch:
  - arm64
  - amd64
# sudo false implies containerized builds
sudo: false


notifications:
    email: false

python:
  - 3.7

cache:
    directories:
    - $HOME/miniconda

env:
  global:
    # Directory where tests are run from
    - CONDA_DEPS="pip nose numpy scipy numba pytest<4 coveralls"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-arm64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS

install:
    - pip install -e .[docs,tests]

script:
    - pytest

after_success:
    - coveralls
